Typos fixed
la-ots/pelican pull request #177
Opened 2022-04-11 17:12 UTC by isralduke

This PR fixes typos across 32 files.

2022-04-12 21:36 UTC, frogpad7 requested changes
Just a few more grammar adjustments to note; the links work perfectly fine.

2022-04-12 21:36 UTC, frogpad7 commented on docs/accessibility/skip-link.md
> +Users who rely keyboard navigation need a way to skip past navigation elements if they are already familiar with the page.
```suggestion
Users who rely on keyboard navigation need a way to skip past navigation elements if they are already familiar with the page.
```

2022-04-12 21:36 UTC, frogpad7 commented on docs/components/pagination.md
> +- You may need to adjust columns sizes for best fit to your project.
```suggestion
- You may need to adjust columns sizes to best fit to your project.
```

2022-04-12 21:36 UTC, frogpad7 commented on docs/components/skip-link.md
> +Users who rely keyboard navigation need a way to skip past navigation elements if they are already familiar with the page.
```suggestion
Users who rely on keyboard navigation need a way to skip past navigation elements if they are already familiar with the page.
```

2022-04-12 21:36 UTC, frogpad7 commented on docs/feature-blocks/call-to-action-double.md
> +  - This Call-to-Action, like the Call-to-Action Single, is not navigation, it’s a persuasion item with two choices you present to the user.
```suggestion
  - This Call-to-Action, like the Call-to-Action Single, is not for navigation; it’s a persuasion item with two choices you present to the user.
```

2022-04-12 21:36 UTC, frogpad7 commented on docs/feature-blocks/call-to-action-single.md
> +  - A Call-to-Action is not navigation, it’s a persuasion item with a link to what you want the user to do.
```suggestion
  - A Call-to-Action is not navigation. It’s a persuasion item with a link to what you want the user to do.
```

2022-04-13 14:05 UTC, frogpad7 submitted a review, later dismissed
All current text changes are much more readable! Nice cleanup!

2022-04-27 19:42 UTC, rltucker reviewed
1. I would argue 'Cards' should actually be 'Card' since other areas use the singular to refer to an element.
2. Why is the 'required' note removed in Radio? I've actually had devs ask how to add it. We can't assume they will know to go to 'Input' to see it. It really should be mentioned as many times as possible.
3. Images: We should keep the 250 character suggestion. 'Short but descriptive is vague'

2022-05-02 16:33 UTC, rltucker approved these changes
Approved

2022-05-03 14:51 UTC, merged